# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('reservation_status', models.IntegerField(blank=True, choices=[(0, b'created'), (1, b'pending'), (2, b'approved')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabel_name', models.CharField(blank=True, max_length=250, null=True)),
                ('tabel_capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, b'created'), (1, b'approved')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Tables'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
