# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': 'Table'},
        ),
    ]
