# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20181124_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Reservation'},
        ),
    ]
