# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20181124_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
    ]
